# .github/workflows/preview.yml
name: Deploy
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pnpm ci:setup
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: deploy-previews
          umbrella-dir: pr-preview
          action: auto
